[QHC-973] Adding improved error, to trace origin in Runcard (#942)
### ORIGINAL PROBLEM:
When executing circuits on the Contralto chip, which has 10 correctly
working qubits out of the 20 available ones. Which concretely is missing
qubit 10 (since its not working well), Qililab breaks because it tries
to compile from qubit 0 to qubit 19 including qubit 10 which should not
be used used. It should only be parked away with flux, when in the
middle of other CZ gates.

#### Circuit that triggered the bug:
```
import qililab as ql
from qibo import Circuit, gates
import numpy as np
ql.logger.setLevel(40)  # Set qililab's logger to a higher level so it only shows error messages
PLATFORM_PATH = '10q_contralto_BSC.yml'
circuit = Circuit(1)
circuit.add(gates.X(0))
circuit.add(gates.M(0))

result = ql.execute(circuit,PLATFORM_PATH,nshots=1000)
print(result.counts())
```

#### Error msg:
```
File "/gpfs/home/bsc/bsc099511/quantum_docu_slurm/QuantumBSC/circuit_ql.py", line 19, in <module>
    result = ql.execute(circuit,PLATFORM_PATH,nshots=10000)
  File "/gpfs/apps/QUANTUM/PYTHON/3.10.13/lib/python3.10/site-packages/qililab/execute_circuit.py", line 117, in execute
    raise e
  File "/gpfs/apps/QUANTUM/PYTHON/3.10.13/lib/python3.10/site-packages/qililab/execute_circuit.py", line 102, in execute
    results = [
  File "/gpfs/apps/QUANTUM/PYTHON/3.10.13/lib/python3.10/site-packages/qililab/execute_circuit.py", line 104, in <listcomp>
    platform.execute(
  File "/gpfs/apps/QUANTUM/PYTHON/3.10.13/lib/python3.10/site-packages/qililab/platform/platform.py", line 1052, in execute
    programs, final_layout = self.compile(program, num_avg, repetition_duration, num_bins, transpilation_config)
  File "/gpfs/apps/QUANTUM/PYTHON/3.10.13/lib/python3.10/site-packages/qililab/platform/platform.py", line 1212, in compile
    module_and_sequencer_per_bus: dict[str, ModuleSequencer] = {
  File "/gpfs/apps/QUANTUM/PYTHON/3.10.13/lib/python3.10/site-packages/qililab/platform/platform.py", line 1216, in <dictcomp>
    self.buses.get(alias=element.bus_alias).instruments, self.buses.get(alias=element.bus_alias).channels
AttributeError: 'NoneType' object has no attribute 'instruments'

  0%|          | 0/1 [00:03<?, ?it/s]
  ```

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>